/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#71a1ff",
        "on-secondary-container": "#684000",
        "tertiary-fixed": "#d8e2ff",
        "primary-container": "#10b981",
        "on-error": "#ffffff",
        "outline": "#6c7a71",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#00422b",
        "on-tertiary-container": "#00367a",
        "on-secondary-fixed": "#2a1700",
        "on-surface-variant": "#3c4a42",
        "on-primary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        "on-primary": "#ffffff",
        "tertiary": "#005ac2",
        "background": "#f9f9ff",
        "on-secondary-fixed-variant": "#653e00",
        "surface-container-low": "#f1f3ff",
        "secondary-container": "#fea619",
        "surface-container-highest": "#dce2f7",
        "on-surface": "#141b2b",
        "on-tertiary-fixed-variant": "#004395",
        "on-primary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#ffb95f",
        "surface-dim": "#d3daef",
        "secondary": "#855300",
        "secondary-fixed": "#ffddb8",
        "surface-tint": "#006c49",
        "surface-container-high": "#e1e8fd",
        "inverse-surface": "#293040",
        "surface-container": "#e9edff",
        "on-tertiary-fixed": "#001a42",
        "primary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#adc6ff",
        "primary": "#006c49",
        "on-background": "#141b2b",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "inverse-primary": "#4edea3",
        "inverse-on-surface": "#edf0ff",
        "surface-variant": "#dce2f7",
        "outline-variant": "#bbcabf",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "16px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xs: "4px",
        base: "8px",
        xl: "32px",
      },
      fontFamily: {
        "title-md": ["Inter"],
        "headline-lg": ["Inter"],
        "caption": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
